#!/usr/bin/env bash
#installs ngnix and configures it to listen on port 80 and return Hello World! when curled
sudo apt-get update
sudo apt-get install -y nginx

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/c404.html

echo "server {
    listen 80;
    error_page 404 /c404.html;
    location = / {
        return 200 'Hello World!';
        add_header Content-Type text/plain;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;
    }
    location = /c404 {
    	root /usr/share/nginx/html;
	internal;
    }
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
