#!/usr/bin/env bash
# Pings an IP address 5 times and passes it as an argument

if [[ $1 =~ ^[0-9]{1.3}\.[0-9]{1.3}\.[0-9]{1.3}\.[0-9]{1.3}$ ]]
then
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
