#!/usr/bin/env bash
# Script that displays numbers from 1 to 100
# If the number is divisible by both 3 and 5, print "FizzBuzz"
# If the number is divisible by 3, print "Fizz"
# If the number is divisible by 5, print "Buzz"
# Otherwise, just print the number.
x=1
while [ $x -le 100 ]
do
	if [ $((x % 3)) -eq 0 ] && [ $((x % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((x % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((x % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$x"
	fi
	((x++))
done
