#!/bin/bash/env bash

# Display username, user id, and home directory path for each user in /etc/passwd

while IFS=: read -r username password userid groupid info homedir shell
do
    # Display the required information
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $homedir"

done < /etc/passwd

