#!/usr/bin/env bash
# This script prints 'Best School' 10 times
# but for the 4th iteration displays 'good luck'
# but for the 8th iteration displays 'bad luck'
x=1
while [ $x -lt 10 ];
do
        if [ $x == 4 ]
        then
		echo "bad luck"
	elif [ $x == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((x++))
done
