#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/new.hosts
echo "127.0.0.2		localhost" > ~/new.hosts
echo "8.8.8.8		facebook.com" >> ~/new.hosts
cp -f ~/new.hosts /etc/hosts
